name: service_catalog_data
description: Data implementation for service_catalog.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  service_catalog_domain:
    path: ../service_catalog_domain

dev_dependencies:
  json_serializable: 6.9.5
  build_runner: ^2.4.13
  freezed: 3.0.6
  injectable_generator: ^2.7.0
  lints: ^6.0.0
  test: ^1.25.0
