name: sample_presentation
description: Sample Flutter UI and BLoC with package DI. No data-layer dependency.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"
resolution: workspace

dependencies:
  injectable: ^2.5.0
  get_it: ^8.0.3
  freezed_annotation: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  sample_domain:
    path: ../sample_domain
  ui_kit:
    path: ../../../shared/ui_kit

dev_dependencies:
  injectable_generator: ^2.7.0
  build_runner: ^2.4.13
  freezed: 3.0.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  app_result:
    path: ../../../shared/app_result
